### ISSUE TITLE
Pin reversal in ESP32 diagram

### ISSUE THREAD

**Issue by SWillSZ** [jango-fx/Adafruit-HUZZAH32-Feather-pinout#3]
Hello,

Quick note - GPIO 25 and GPIO 26 are reversed in your pinout for the ESP32 Huzzah. Might be best to patch it up - I used it from the web, and ended up realizing the issue.

William

**Comment by jango-fx** [comment]
👍 thx for pointing it out
I'll try to fix it the next few days
